apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: container
          image: 061039791229.dkr.ecr.us-east-1.amazonaws.com/pocs/ci-cd-go:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
      - ecr-secret
