apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: container
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/my-repository:latest
          ports:
            - containerPort: 8080
